In [5]:
import pandas as pd
from pandas import Series, DataFrame
import numpy as np
import sqlite3

In [8]:
# Read DF from SQLite DB
conn = sqlite3.connect("finals.db")
df = pd.read_sql_query("SELECT * FROM results", conn)
df

,index,Date,COAST,EAST,FAR_WEST,NORTH,NORTH_C,SOUTHERN,SOUTH_C,WEST,KDAL_TemperatureF,KHOU_TemperatureF,KSAT_TemperatureF
0,0,2014-01-01 00:00:00,8913.01,1491.29,1783.56,968.27,11923.53,3230.89,6191.00,1312.92,68.0,62.1,60.1
1,1,2014-01-01 07:00:00,8665.54,1588.44,1819.77,1074.47,13154.07,3155.70,6492.82,1443.59,39.9,48.0,43.0
2,2,2014-01-01 08:00:00,8661.20,1573.47,1818.99,1064.53,12956.24,3159.13,6427.81,1425.48,39.0,48.0,41.0
3,3,2014-01-01 09:00:00,8778.05,1531.44,1784.43,1048.56,12628.14,3200.12,6206.40,1366.63,37.9,48.0,42.1
4,4,2014-01-01 10:00:00,8759.46,1459.10,1774.87,999.31,12160.81,3201.32,6065.07,1297.79,37.9,48.0,45.0
5,5,2014-01-01 11:00:00,8661.44,1366.90,1765.61,954.26,11608.01,3192.11,5872.33,1248.21,37.0,48.9,44.1
6,6,2014-01-01 12:00:00,8595.00,1274.72,1732.35,901.68,11001.45,3117.07,5683.01,1191.92,36.0,48.0,42.1
7,7,2014-01-01 13:00:00,8486.33,1202.35,1692.05,859.03,10404.83,3040.75,5464.22,1113.09,36.0,48.9,44.1
8,8,2014-01-01 14:00:00,8413.84,1141.63,1665.00,820.15,9909.38,2969.03,5301.20,1076.58,37.0,48.9,39.9
9,9,2014-01-01 14:00:00,8413.84,1141.63,1665.00,820.15,9909.38,2969.03,5301.20,1076.58,37.0,48.2,39.9
10,10,2014-01-01 15:00:00,8391.99,1129.52,1648.70,806.77,9639.97,2916.82,5250.64,1042.28,39.9,51.1,45.0
11,11,2014-01-01 16:00:00,8502.20,1145.95,1645.29,817.61,9588.03,2889.81,5240.10,1022.27,45.0,51.8,48.9
12,12,2014-01-01 16:00:00,8502.20,1145.95,1645.29,817.61,9588.03,2889.81,5240.10,1022.27,45.0,55.0,48.9
13,13,2014-01-01 17:00:00,9015.99,1239.90,1667.21,868.30,10157.83,2954.37,5538.01,1075.33,55.0,59.0,52.0
14,14,2014-01-01 18:00:00,9321.76,1293.21,1748.86,929.86,11009.35,3135.89,6004.74,1206.22,57.0,63.0,55.0
15,15,2014-01-01 19:00:00,9237.46,1297.98,1757.85,951.74,11037.53,3134.35,6003.72,1229.71,62.1,64.0,57.2
16,16,2014-01-01 19:00:00,9237.46,1297.98,1757.85,951.74,11037.53,3134.35,6003.72,1229.71,62.1,64.0,57.0
17,17,2014-01-01 20:00:00,9083.86,1285.52,1765.35,970.99,11017.50,3088.60,5877.55,1234.12,64.9,64.9,57.9
18,18,2014-01-01 20:00:00,9083.86,1285.52,1765.35,970.99,11017.50,3088.60,5877.55,1234.12,64.9,64.4,57.9
19,19,2014-01-01 20:00:00,9083.86,1285.52,1765.35,970.99,11017.50,3088.60,5877.55,1234.12,64.9,64.4,57.9
20,20,2014-01-01 21:00:00,8821.17,1246.30,1766.93,984.27,11058.38,2997.55,5718.96,1233.62,66.9,64.0,59.0
21,21,2014-01-01 22:00:00,8458.50,1174.67,1750.19,989.05,11051.52,2854.88,5411.72,1218.83,69.1,64.0,60.8
22,22,2014-01-01 22:00:00,8458.50,1174.67,1750.19,989.05,11051.52,2854.88,5411.72,1218.83,69.1,64.0,60.1
23,23,2014-01-01 23:00:00,7985.53,1115.31,1730.29,994.14,11060.61,2654.51,5112.15,1195.01,70.0,62.6,60.8
24,24,2014-01-01 23:00:00,7985.53,1115.31,1730.29,994.14,11060.61,2654.51,5112.15,1195.01,70.0,62.6,60.1
25,25,2014-01-01 23:00:00,7985.53,1115.31,1730.29,994.14,11060.61,2654.51,5112.15,1195.01,70.0,63.0,60.8
26,26,2014-01-01 23:00:00,7985.53,1115.31,1730.29,994.14,11060.61,2654.51,5112.15,1195.01,70.0,63.0,60.1
27,27,2014-01-02 00:00:00,7595.51,1095.09,1718.52,1009.48,11249.05,2477.62,4895.86,1171.73,39.0,46.9,51.1
28,28,2014-01-02 01:00:00,7357.58,1116.22,1722.25,1023.54,11653.57,2351.48,4788.91,1170.24,64.9,60.1,60.1
29,29,2014-01-02 02:00:00,7255.99,1172.09,1741.56,1047.65,12184.76,2274.57,4824.30,1201.09,62.6,60.1,59.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
33356,33356,2015-12-30 03:00:00,8309.53,1325.04,2072.61,886.36,11767.94,2475.58,5397.47,1324.54,42.1,53.6,46.9
33357,33357,2015-12-30 04:00:00,8473.53,1354.70,2088.38,910.81,12225.14,2515.67,5497.54,1369.43,42.1,53.1,46.0
33358,33358,2015-12-30 05:00:00,8919.56,1426.08,2117.26,963.09,13036.45,2631.74,5821.83,1437.86,42.1,53.1,46.0
33359,33359,2015-12-30 05:00:00,8919.56,1426.08,2117.26,963.09,13036.45,2631.74,5821.83,1437.86,42.1,53.1,46.0
33360,33360,2015-12-30 06:00:00,9461.71,1526.46,2170.63,1045.77,14039.80,2828.68,6230.24,1529.41,39.9,53.1,46.0
33361,33361,2015-12-30 07:00:00,9770.14,1550.40,2218.86,1094.02,14635.34,2968.36,6440.08,1600.14,39.0,51.1,46.0
33362,33362,2015-12-30 08:00:00,9907.27,1565.71,2222.28,1097.08,14499.63,3026.86,6429.50,1590.47,37.9,50.0,46.9
33363,33363,2015-12-30 08:00:00,9907.27,1565.71,2222.28,1097.08,14499.63,3026.86,6429.50,1590.47,37.9,50.0,46.9
33364,33364,2015-12-30 09:00:00,10131.33,1582.16,2196.93,1080.35,14030.66,3094.36,6380.38,1567.28,37.0,50.0,46.9
33365,33365,2015-12-30 09:00:00,10131.33,1582.16,2196.93,1080.35,14030.66,3094.36,6380.38,1567.28,37.0,50.0,46.9
33366,33366,2015-12-30 10:00:00,10276.84,1573.69,2150.23,1045.51,13474.88,3159.17,6257.65,1506.07,36.0,52.0,46.9
33367,33367,2015-12-30 10:00:00,10276.84,1573.69,2150.23,1045.51,13474.88,3159.17,6257.65,1506.07,36.0,52.0,46.9
33368,33368,2015-12-30 10:00:00,10276.84,1573.69,2150.23,1045.51,13474.88,3159.17,6257.65,1506.07,36.0,52.0,46.9
33369,33369,2015-12-30 11:00:00,10227.89,1521.80,2097.25,1012.33,12847.95,3164.78,6127.61,1433.15,35.1,51.1,46.9
33370,33370,2015-12-30 12:00:00,10085.62,1467.99,2045.06,970.44,12233.11,3125.87,5893.27,1360.51,35.1,51.1,48.0
33371,33371,2015-12-30 13:00:00,10015.44,1410.13,2010.42,946.87,11741.51,3061.09,5694.41,1302.64,36.0,52.0,46.9
33372,33372,2015-12-30 14:00:00,9941.15,1404.29,1983.12,926.71,11342.12,3000.68,5611.37,1245.46,35.1,52.0,48.0
33373,33373,2015-12-30 14:00:00,9941.15,1404.29,1983.12,926.71,11342.12,3000.68,5611.37,1245.46,35.1,52.0,48.0
33374,33374,2015-12-30 15:00:00,9935.59,1382.95,1976.95,909.86,11134.44,2967.37,5569.09,1225.12,39.9,53.1,50.0
33375,33375,2015-12-30 16:00:00,9986.84,1416.04,1986.79,914.86,11252.19,2982.67,5655.26,1237.14,39.9,52.0,51.1
33376,33376,2015-12-30 16:00:00,9986.84,1416.04,1986.79,914.86,11252.19,2982.67,5655.26,1237.14,39.9,52.0,51.1
33377,33377,2015-12-30 16:00:00,9986.84,1416.04,1986.79,914.86,11252.19,2982.67,5655.26,1237.14,43.0,52.0,51.1
33378,33378,2015-12-30 17:00:00,10438.90,1514.34,2021.90,980.37,12205.46,3076.63,6077.50,1297.10,46.0,53.1,54.0
33379,33379,2015-12-30 18:00:00,10540.62,1611.37,2114.01,1039.59,13148.80,3246.89,6564.19,1399.36,50.0,53.6,55.9
33380,33380,2015-12-30 18:00:00,10540.62,1611.37,2114.01,1039.59,13148.80,3246.89,6564.19,1399.36,50.0,55.0,55.9
33381,33381,2015-12-30 19:00:00,10393.96,1594.82,2136.54,1048.06,13256.88,3234.29,6608.61,1416.04,51.1,55.9,59.0
33382,33382,2015-12-30 20:00:00,10234.54,1589.22,2157.42,1053.12,13295.73,3200.63,6572.43,1426.48,51.1,55.9,60.1
33383,33383,2015-12-30 21:00:00,9934.60,1524.16,2162.56,1036.04,13157.20,3129.51,6429.56,1408.51,52.0,55.9,60.1
33384,33384,2015-12-30 22:00:00,9463.58,1471.28,2134.48,993.17,12685.79,3017.99,6199.83,1368.31,53.1,57.0,59.0
33385,33385,2015-12-30 23:00:00,8958.61,1397.51,2097.77,950.54,12114.54,2861.11,5891.62,1324.19,51.1,55.9,57.9